### PR TITLE
added scroll bar on my music pages

### PR DESCRIPTION
**Pull request by AlexxyQQ**
Just added a simple scroll bar widget to the listview builder in the my music pages
Also added empty screens to all the tabviews in the my screen pages.

### CODE REVIEW

**Comment by AlexxyQQ** [comment]
Though the page needed a scrollbar 🙂

**Comment by Sangwan5688** [comment]
Please share screenshots as well if possible

**Comment by AlexxyQQ** [comment]
Screenshot_1680838053
Screenshot_1680838486

**Comment by Sangwan5688** [comment]
Cool, please fix the formatting as well. It's breaking the build

**Comment by Sangwan5688** [comment]
Thanks for the PR; really appreciate it. Sorry, I wasn't able to merge your PR due to formatting issues & outdated code, and no actions were taken. So, I have just cloned the functionality.

**Pull request closed without merging**
