### PR TITLE
fixed Visual Bug

### PR DESCRIPTION
**Pull request by badushaebrahim**
fixed Visual Bug in issue
#284 Visual Bug in Android Mobile App (Overflow error in Playlist Page) #284

### CODE REVIEW

**Comment by Sangwan5688** [comment]
Please fix the formatting issue

**Comment by badushaebrahim** [comment]
Can you explain i don't understand

**Comment by Surendrajat** [comment]
@badushaebrahim you need to run `flutter format .`

**Comment by Surendrajat** [comment]
@badushaebrahim you need to run `flutter format .`

**Comment by badushaebrahim** [comment]
@Surendrajat thanks bro its ready @Sangwan5688  thanks for the chance

**Pull request merged**
