### PR TITLE
for visual bug

### PR DESCRIPTION
**Pull request by badushaebrahim**
for download.dart pop over flow for android

### CODE REVIEW

**Comment by Sangwan5688** [comment]
Please provide some screenshots or something clearly showing the visual changes made.

**Comment by badushaebrahim** [comment]
screenshot of error
WhatsApp Image 2022-04-11 at 7 47 42 PM

**Comment by badushaebrahim** [comment]
it is for the yes button overflow

**Comment by badushaebrahim** [comment]
sorry about that

**Comment by Sangwan5688** [comment]
wasn't this already covered in previous PR?

**Comment by badushaebrahim** [comment]
so it was merged

**Pull request closed without merging**
