### PR TITLE
replace overflowing text in song/album list with ellipsis(...)

### PR DESCRIPTION
**Pull request by Surendrajat**
This PR
- fixed overflowing text in songs/artists/albums list with ellipsis(...)
- Downloaded/My Music songs name to max 2 line width.

~Search screen is not done yet.~

### CODE REVIEW

**Comment by Sangwan5688** [comment]
Have you included the latest ones? Related to search results?

**Comment by Surendrajat** [comment]
Yes. All done I think.

**Comment by Sangwan5688** [comment]
Search/search.dart is missing.

**Comment by Surendrajat** [comment]
Seems like you did it already.

**Comment by Sangwan5688** [comment]
Ahh, Ok Ok

**Pull request merged**
