### PR TITLE
Autoscroll when new song is played

### PR DESCRIPTION
**Pull request by BrightDV**
Hi,

Since the latest version, there was a small overflow of the song's artwork in the bottom of the `Now Playing` section
Screenshot_20211220-192824
I have removed it by changing the color of the `Container` and its size.
Screenshot_20211220-192622
Also, I have also modified the behavior of the `SlidingUpPanel`
Now, the items aren't seen behind the title.

Before:
Screenshot_20211220-192845

After:
Screenshot_20211220-192638

It will also help to add the auto-scroll to the played item of the list when `Now Playing` is shown.

### CODE REVIEW

**Comment by Sangwan5688** [comment]
Umm, Actually that transparent now playing is intentional, I specifically wrote code for that. I personally think it looks cool that way. If there's something else which you can do without removing that shading then it would be much better.
Also as for auto-scrolling, well ya it can be implemented. You wanna try it?
There's already a mediaItem listener in that listView. So using that we are already checking current playing item. There's also a scrollController there. So just add attach a listener to scrollController for mediaItem Stream so that it changes position according to the index of currently playing song. I think each listview is of height around 60-70. So just change scroll position to 60*index of that song. And the listener will automatically change position of scroll each time song changes.

**Comment by BrightDV** [comment]
>Actually that transparent now playing is intentional

OK, I will keep the shading
>You wanna try it?

Sure! But I'm new to Flutter, so it can take a while...
 
>There's already a mediaItem listener in that listView. So using that we are already checking current playing item.

I see, but what if there is a duplicate of a stream in the section? Is there a way to get the index of the played item in the queue?

**Comment by Sangwan5688** [comment]
> I see, but what if there is a duplicate of a stream in the section? Is there a way to get the index of the played item in the queue?

Each item has a unique id. So there won't be any duplicates there. The stream will provide you with mediaItem and queue. So just find the index of that mediaItem in Queue

**Comment by BrightDV** [comment]
So I have tried to do so, but I faced some issues:
- I didn't know where to put the code in `NowPlayingStream` : I have put it in its builder class [here](https://github.com/BrightDV/BlackHole/blob/3f6c211c7d6aaad00cb3e6b4537fbc6aa731b339/lib/Screens/Player/audioplayer.dart#L1101). It worked well, but not when the user scrolled because it tried to scroll to the song's position. Is there a way to do a listener of the `ControllButtons` instead, or something like that?
- Also, there were some speed issues as the scroll was in the builder class. So for the moment, I removed the transition when a new song is played.

**Comment by Sangwan5688** [comment]
> It worked well, but not when the user scrolled because it tried to scroll to the song's position.

Check if now playing panel is open or not. If it's open don't scroll, if it's closed scroll. So that whenever user open the panel now playing shows at the top.

**Comment by BrightDV** [comment]
So I have added it by adding a check if the panel is open, and it scrolls too when the user clicks on a new song in now playing.
But there is still a problem: when the user skips the song twice, it doesn't update the now playing section, so the scroll keep its position. I have tried to call it when a button is skip, but it does not work because it doesn't update the section.

**Comment by Sangwan5688** [comment]
> So I have added it by adding a check if the panel is open, and it scrolls too when the user clicks on a new song in now playing. But there is still a problem: when the user skips the song twice, it doesn't update the now playing section, so the scroll keep its position. I have tried to call it when a button is skip, but it does not work because it doesn't update the section.

Umm, I think you did the opposite. See whenever a user skips the song or it skips automatically, the queueIndex will change. So you have to listen to that change in queueIndex. Now if sliding panel is open, that means user is scrolling through the list, so you don't want the app to scroll that time. Whereas if sliding panel is closed. That means user isn't scrolling anything, then that time you want to change the scroll position so that when user opens sliding panel, current songs shows up at the top.

**Comment by BrightDV** [comment]
>Now if sliding panel is open, that means user is scrolling through the list, so you don't want the app to scroll that time. Whereas if sliding panel is closed. That means user isn't scrolling anything, then that time you want to change the scroll position so that when user opens sliding panel, current songs shows up at the top.
Then you can add some functionality on onClick function too. So that it scrolls when user clicks any song from the list.

Yes I have added that, sorry for my english.
See the code, I have added a function that verify if the panel is closed or not. If it is closed, the scroll changes its position on new song. However, if it is open, it will not scroll. I have also added a call to this function when user tap on a song inside the now playing section.
>So you have to listen to that change in queueIndex.

Ok I will try that, but how do you do a listener?

**Comment by Sangwan5688** [comment]
> Ok I will try that, but how do you do a listener?
There's already a streamlistener there, so it will automatically update everything inside that `streamBuilder`. I think you have already done that

**Comment by BrightDV** [comment]
>There's already a streamlistener there, so it will automatically update everything inside that streamBuilder. I think you have already done that

I verified and yes, I have added that. The problem is when user skip song twice as for a strange reason, it don't update the scroll position. The first time, yes but not the second.
I will try to readd the previous scroll which scrolls everytime to see if it fix this problem.

**Comment by BrightDV** [comment]
I think it will need some work for this feature and I will not have à lot of time to code in the next days so I close it for the moment but I keep the code. I will open a pr if I add it.

**Comment by Sangwan5688** [comment]
Ok, no worries

**Pull request closed without merging**
