### PR TITLE
fixed the song speed button

### PR DESCRIPTION
**Pull request by DecodeAndCode**
Close  - https://github.com/Sangwan5688/BlackHole/issues/514

Padded the text in gesture detector by 20 pixel from bottom.

### CODE REVIEW

**Comment by Sangwan5688** [comment]
I doubt that bug is relevant anymore. I have already made some changes in the seek bar which makes sure there is enough padding

**Comment by DecodeAndCode** [comment]
Actually I used the app even I thought it should have more space like ios apple music which looks more good thats why I gave it a try.

But I the older version is also nice.

can you suggest some issues to me as I am a begineer and want to contribute.

**Comment by Sangwan5688** [comment]
You can go over issues, and if something is simple you can try it. As for this, I'll test it and will think if it's required or not. If it is, then I'll merge

**Comment by Sangwan5688** [comment]
Closing this as it's no longer an issue

**Pull request closed without merging**
