### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by shaan-mephobic**
I've replaced `Container` with `AnimatedContainer` so the gradient can smoothly transition to the next song's gradient.(change the duration of animation to what you like. I've kept it at 300ms so it doesn't look like the app is slow)
Check out [here](https://drive.google.com/file/d/1nk6OH2SzB8mmlBvTfbpNF6bw92wuHhz5/view?usp=sharing).

And I've added `AutomaticKeepAliveClientMixin` which will keep the position of the ListViews in memory.
Check out [here](https://drive.google.com/file/d/11d5wmr5950j68KgeeUNWUYSTN1rn6ROd/view?usp=sharing).

Also do consider bumping up the artwork quality in [audioplayer](https://drive.google.com/file/d/1hx29dPHhO7D_VxK4eglInUzRLX6LsOYR/view?usp=sharing) screen for offline songs alone. 200 is good for ListTile but for the audioplayer screen consider putting something like 350.

### CODE REVIEW

**Review by Sangwan5688 — COMMENTED** [review]
Everything looks fine. As for duration use something around 200. Now coming over to build failing, you can fetch latest commits and then update PR. And please make sure that formatting is according to Flutter v2.5.

**Comment by Sangwan5688** [comment]
One more thing increase artwork size too along with that. Make it 350 or whatever you thing is fine.

**Comment by Sangwan5688** [comment]
Thanks for PR

**Comment by shaan-mephobic** [comment]
I haven't updated the artwork yet. I'll do another PR for it

**Comment by Sangwan5688** [comment]
No worries about that, I have already done it and also adjusted duration so as it look good

**Comment by shaan-mephobic** [comment]
Alright cool then

**Pull request merged**
