### PR TITLE
Compress Large Images and Update docs

### PR DESCRIPTION
**Pull request by AnilSeervi**
- Compress Large Images used in [Website](https://sangwan5688.github.io/BlackHole/) for better performance
---
> Also consider lazy loading of these images

### CODE REVIEW

**Comment by Sangwan5688** [comment]
Thanks for PR. Coming over to compression, can you compress other images too. There are some screenshots inside `fastlane` folder. Compress them enough that they good enough in readme.

Also, there are some images in `Assets` too, don't compress all of them just compress large ones.

**Comment by AnilSeervi** [comment]
> Thanks for PR. Coming over to compression, can you compress other images too. There are some screenshots inside `fastlane` folder. Compress them enough that they good enough in readme.
> 
> Also, there are some images in `Assets` too, don't compress all of them just compress large ones.

Sure. Will do.

**Comment by AnilSeervi** [comment]
- Add lazy loading for images that are below
- Add Google Fonts cdn with preconnect
- dynamic copyright year update
- format non-uniform tags

**Comment by Sangwan5688** [comment]
Cool thanks a lot for that :). It's all done, right? Or do you have something else too?

**Comment by AnilSeervi** [comment]
> 
> 
> Cool thanks a lot for that :). It's all done, right? Or do you have something else too?

Everything I wished to do is done @Sangwan5688. For Now :)

**Comment by Sangwan5688** [comment]
Cool, thanks for PR :)

**Comment by AnilSeervi** [comment]
Now the docs site is much faster!!! 🎉🎉

**Pull request merged**
