### PR TITLE
Copyright Year Update !

### PR DESCRIPTION
**Pull request by thealidev**

### CODE REVIEW

**Comment by Akshay-Arjun** [comment]
@thealidev the year on website is [dynamically updated](https://github.com/Sangwan5688/BlackHole/pull/125#issuecomment-933186927)  but why don't you change the "windows - releasing soon" in download section to download from github and add the github releases link ;) .
image

**Comment by thealidev** [comment]
I will provide you windows release
Will you update it then on github releases

**Comment by thealidev** [comment]
How i need to patch it
I know how to build it

**Comment by Akshay-Arjun** [comment]
I think you didn't misunderstood me. The windows build is already available in [releases page](https://github.com/Sangwan5688/BlackHole/releases). Just change the text and redirect it to releases pages.

**Comment by Sangwan5688** [comment]
I might remove the website code from this repo soon. The main website is hosted at github.com/sangwan5688/sangwan5688.github.io, so if you have PRs for that, please raise it there

**Pull request closed without merging**
