### PR TITLE
Add support for French language

### PR DESCRIPTION
**Pull request by BrightDV**
Hello,

I added French language support for the app and a French README. 
I have changed a little the English README to access the French one
For the next versions, it would be nice to have a Weblate or something like that to translate easier

Related to [#184](https://github.com/Sangwan5688/BlackHole/issues/184)

### CODE REVIEW

**Comment by Sangwan5688** [comment]
Thanks, will look for some easy way in future

**Comment by BrightDV** [comment]
Sorry for reopening the pr, but it seems like I forgot a ',' in a [file](https://github.com/Sangwan5688/BlackHole/blob/main/lib/localization/app_fr.arb#L6) which broke the build
I tested it, and it should work as expected, sorry for the mistake

**Comment by Sangwan5688** [comment]
No worries, there were already some issues with formatting so build was already broken. That's why I ignored it I thought it's coz of those formatting issues. Anyway, I will fix it with next commit. You needn't worry.

**Comment by Sangwan5688** [comment]
Ok, So I have added weblate support for blackhole. I never expected them to support arb files but turned out that they do support it. So, I added the project. In future, you can do translations there.
URL: https://hosted.weblate.org/projects/blackhole/localization/

**Pull request merged**
